In [590]:
import numpy as np

In [591]:
from sklearn import metrics

In [592]:
from sklearn.model_selection import train_test_split

In [593]:
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score, log_loss

In [594]:
from sklearn.naive_bayes import GaussianNB

In [595]:
X = np.array([
[7.0,3.2,4.7,1.4],
[6.4,3.2,4.5,1.5],
[6.9,3.1,4.9,1.5],
[5.5,2.3,4.0,1.3],
[6.5,2.8,4.6,1.5],
[5.7,2.8,4.5,1.3],
[6.3,3.3,4.7,1.6],
[4.9,2.4,3.3,1.0],
[6.6,2.9,4.6,1.3],
[5.2,2.7,3.9,1.4],
[5.0,2.0,3.5,1.0],
[5.9,3.0,4.2,1.5],
[6.0,2.2,4.0,1.0],
[6.1,2.9,4.7,1.4],
[5.6,2.9,3.6,1.3],
[6.7,3.1,4.4,1.4],
[5.6,3.0,4.5,1.5],
[5.8,2.7,4.1,1.0],
[6.2,2.2,4.5,1.5],
[5.6,2.5,3.9,1.1],
[5.9,3.2,4.8,1.8],
[6.1,2.8,4.0,1.3],
[6.3,2.5,4.9,1.5],
[6.1,2.8,4.7,1.2],
[6.4,2.9,4.3,1.3],
[6.6,3.0,4.4,1.4],
[6.8,2.8,4.8,1.4],
[6.7,3.0,5.0,1.7],
[6.0,2.9,4.5,1.5],
[5.7,2.6,3.5,1.0],
[5.5,2.4,3.8,1.1],
[5.5,2.4,3.7,1.0],
[5.8,2.7,3.9,1.2],
[6.0,2.7,5.1,1.6],
[5.4,3.0,4.5,1.5],
[6.0,3.4,4.5,1.6],
[6.7,3.1,4.7,1.5],
[6.3,2.3,4.4,1.3],
[5.6,3.0,4.1,1.3],
[5.5,2.5,4.0,1.3],
[5.5,2.6,4.4,1.2],
[6.1,3.0,4.6,1.4],
[5.8,2.6,4.0,1.2],
[5.0,2.3,3.3,1.0],
[5.6,2.7,4.2,1.3],
[5.7,3.0,4.2,1.2],
[5.7,2.9,4.2,1.3],
[6.2,2.9,4.3,1.3],
[5.1,2.5,3.0,1.1],
[5.7,2.8,4.1,1.3],
[6.3,3.3,6.0,2.5],
[5.8,2.7,5.1,1.9],
[7.1,3.0,5.9,2.1],
[6.3,2.9,5.6,1.8],
[6.5,3.0,5.8,2.2],
[7.6,3.0,6.6,2.1],
[4.9,2.5,4.5,1.7],
[7.3,2.9,6.3,1.8],
[6.7,2.5,5.8,1.8],
[7.2,3.6,6.1,2.5],
[6.5,3.2,5.1,2.0],
[6.4,2.7,5.3,1.9],
[6.8,3.0,5.5,2.1],
[5.7,2.5,5.0,2.0],
[5.8,2.8,5.1,2.4],
[6.4,3.2,5.3,2.3],
[6.5,3.0,5.5,1.8],
[7.7,3.8,6.7,2.2],
[7.7,2.6,6.9,2.3],
[6.0,2.2,5.0,1.5],
[6.9,3.2,5.7,2.3],
[5.6,2.8,4.9,2.0],
[7.7,2.8,6.7,2.0],
[6.3,2.7,4.9,1.8],
[6.7,3.3,5.7,2.1],
[7.2,3.2,6.0,1.8],
[6.2,2.8,4.8,1.8],
[6.1,3.0,4.9,1.8],
[6.4,2.8,5.6,2.1],
[7.2,3.0,5.8,1.6],
[7.4,2.8,6.1,1.9],
[7.9,3.8,6.4,2.0],
[6.4,2.8,5.6,2.2],
[6.3,2.8,5.1,1.5],
[6.1,2.6,5.6,1.4],
[7.7,3.0,6.1,2.3],
[6.3,3.4,5.6,2.4],
[6.4,3.1,5.5,1.8],
[6.0,3.0,4.8,1.8],
[6.9,3.1,5.4,2.1],
[6.7,3.1,5.6,2.4],
[6.9,3.1,5.1,2.3],
[5.8,2.7,5.1,1.9],
[6.8,3.2,5.9,2.3],
[6.7,3.3,5.7,2.5],
[6.7,3.0,5.2,2.3],
[6.3,2.5,5.0,1.9],
[6.5,3.0,5.2,2.0],
[6.2,3.4,5.4,2.3],
[5.9,3.0,5.1,1.8]])

In [596]:
Y = np.array([1,1,1,1,1,1,1,1,1,1,
             1,1,1,1,1,1,1,1,1,1,
             1,1,1,1,1,1,1,1,1,1,
             1,1,1,1,1,1,1,1,1,1,
             1,1,1,1,1,1,1,1,1,1,
             0,0,0,0,0,0,0,0,0,0,
             0,0,0,0,0,0,0,0,0,0,
             0,0,0,0,0,0,0,0,0,0,
             0,0,0,0,0,0,0,0,0,0,
             0,0,0,0,0,0,0,0,0,0])


In [597]:
clf = GaussianNB()

In [598]:
clf.fit(X, Y)

GaussianNB()

In [599]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.20)

In [600]:
clf.fit(X_train, Y_train)

GaussianNB()

In [601]:
y_pred_train = clf.predict(X_train)

In [602]:
y_pred_train

array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0])

In [603]:
Y_train

array([0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0])

In [604]:
x_prob_train = clf.predict_proba(X_train)

In [605]:
x_prob_test = clf.predict_proba(X_test)

In [606]:
confusion_train = metrics.confusion_matrix(Y_train, y_pred_train)

In [607]:
print(confusion_train)

[[37  2]
 [ 2 39]]


In [608]:
tn = confusion_train[0,0]
fp = confusion_train[0,1]
specificity_train = tn/(fp+tn)

In [609]:
print("Accuracy: ",accuracy_score(Y_train, y_pred_train))
print("Sensitivity : ",recall_score(Y_train, y_pred_train))
print("Precision: ",precision_score(Y_train, y_pred_train))
print("F1: ",f1_score(Y_train, y_pred_train))
print("Log loss: ",log_loss(Y_train, x_prob_train))
print("Specificity: ", specificity_train)

Accuracy:  0.95
Sensitivity :  0.9512195121951219
Precision:  0.9512195121951219
F1:  0.9512195121951219
Log loss:  0.14224008621387355
Specificity:  0.9487179487179487


In [610]:
y_pred_test = clf.predict(X_test)

In [611]:
y_pred_test

array([1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1])

In [612]:
Y_test

array([0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0])

In [613]:
confusion_test = metrics.confusion_matrix(Y_test, y_pred_test)

In [614]:
print(confusion_test)

[[9 2]
 [0 9]]


In [615]:
tn = confusion_test[0,0]
fp = confusion_test[0,1]
specificity_test = tn/(fp+tn)

In [616]:
print("Accuracy: ",accuracy_score(Y_test, y_pred_test))
print("Sensitivity : ",recall_score(Y_test, y_pred_test))
print("Precision: ",precision_score(Y_test, y_pred_test))
print("F1: ",f1_score(Y_test, y_pred_test))
print("Log loss: ",log_loss(Y_test, x_prob_test))
print("Specificity: ", specificity_test)

Accuracy:  0.9
Sensitivity :  1.0
Precision:  0.8181818181818182
F1:  0.9
Log loss:  0.2727892766964816
Specificity:  0.8181818181818182
